apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-acme-issuer
  labels:
    app: cert-manager
    component: step-ca-integration
spec:
  acme:
    # step-ca ACME server URL
    server: "{{ .Values.spec.stepCA.url }}/acme/{{ .Values.spec.stepCA.provisioner }}/directory"
    # Email for ACME registration
    email: cluster@goldentooth.net
    # Private key secret
    privateKeySecretRef:
      name: step-ca-acme-private-key
    # Custom CA bundle for step-ca
    caBundle: {{ .Values.spec.stepCA.rootCA | b64enc | quote }}
    # DNS-01 solver for domain validation
    solvers:
    - dns01:
        route53:
          region: us-east-1
          accessKeyID: "{{ .Values.spec.aws.accessKeyID }}"
          secretAccessKeySecretRef:
            name: cert-manager-route53-credentials
            key: secret-access-key
      selector:
        dnsZones:
        - "goldentooth.net"