apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-acme-issuer
  labels:
    app: cert-manager
    component: step-ca-integration
spec:
  acme:
    # step-ca ACME server URL
    server: "{{ .Values.spec.stepCA.url }}/acme/{{ .Values.spec.stepCA.provisioner }}/directory"
    # Email for ACME registration
    email: cluster@goldentooth.net
    # Private key secret
    privateKeySecretRef:
      name: step-ca-acme-private-key
    # Custom CA bundle for step-ca
    caBundle: {{ .Values.spec.stepCA.rootCA | b64enc | quote }}
    # HTTP01 solver for domain validation
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}
    - dns01:
        webhook:
          groupName: acme.cert-manager.io
          solverName: step-ca-solver